2019-12-30 23:24:01,425 ERROR: Exception on /reset_password_request [POST] [in C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\app\routes.py", line 161, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\app\email.py", line 19, in send_password_reset_email
    html_body=render_template('email/reset_password.html',
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\app\../templates\email\reset_password.html", line 4, in <module>
    <a href="{{ url_for('reset password', token=token, _external=True) }}">click here
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset password' with values ['token']. Did you mean 'reset_password' instead?
2019-12-30 23:24:36,159 INFO: Microblog startup [in C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\app\__init__.py:47]
2019-12-30 23:29:32,227 INFO: Microblog startup [in C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\app\__init__.py:47]
2019-12-30 23:39:47,476 INFO: Microblog startup [in C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\app\__init__.py:47]
2019-12-30 23:40:13,921 INFO: Microblog startup [in C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\app\__init__.py:47]
2019-12-30 23:42:01,798 INFO: Microblog startup [in C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\app\__init__.py:47]
2019-12-30 23:42:17,841 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6MSwiZXhwIjoxNTc3NzcyOTQ2LjE5MzY4NDZ9.X9TQB2tsGsoUMVn1mSbkOrE6olMnmNQ3AxNhSI-DDSQ [POST] [in C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\app\routes.py", line 169, in reset_password
    user = User.verify_reset_password_token(token)
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\app\models.py", line 81, in verify_reset_password_token
    return User.query.get(id)
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\sqlalchemy\orm\query.py", line 982, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\sqlalchemy\orm\query.py", line 1052, in _get_impl
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Incorrect number of values in identifier to formulate primary key for query.get(); primary key columns are 'user.id'
2019-12-30 23:42:18,912 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6MSwiZXhwIjoxNTc3NzcyOTQ2LjE5MzY4NDZ9.X9TQB2tsGsoUMVn1mSbkOrE6olMnmNQ3AxNhSI-DDSQ [POST] [in C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\app\routes.py", line 169, in reset_password
    user = User.verify_reset_password_token(token)
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\app\models.py", line 81, in verify_reset_password_token
    return User.query.get(id)
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\sqlalchemy\orm\query.py", line 982, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "C:\Users\Esther Goldberg\PycharmProjects\Esther Goldberg Final Project\venv\lib\site-packages\sqlalchemy\orm\query.py", line 1052, in _get_impl
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Incorrect number of values in identifier to formulate primary key for query.get(); primary key columns are 'user.id'
